:bug: Fix template error causing email generation to fail
Error: 'can't slice item of type int' at line 272

The template tried to format a date using slice on an int, which
fails. Simplified to use GitHub's relative date syntax instead:
'updated:<30days'

This fixes the failure in email generation introduced in PR #164.

Signed-off-by: Todd Sanders <tsanders@redhat.com>